#!/bin/bash

#set -x
{ 
  tput smcup && clear
libname=$(dirname "$0")
cd $libname

printf "Enter a Commit message: "
read -r  message
git add *
git commit -m "$message" 
git push; 

printf "Commit and push complete.\nEnter any key to continue... "
read -r
tput rmcup

}

