#!/bin/bash
libname=$(dirname "$0")
cd $libname
#set -x
bob(){ 
  tput smcup && clear


printf "Enter a Commit message: "
read -r  message
git add *
git commit -m "$message" 
git push; 

printf "Commit and push complete.\nEnter any key to continue... "
read -r
tput rmcup

}

addgit=$( git add * )
whiptail --infobox "$( echo $addgit )" $(stty size)
NAME=$(whiptail --inputbox "Please enter Comit message:" $(stty size) 3>&1 1>&2 2>&3)
NAME2=$(whiptail --msgbox  "$(echo $( git commit -m $NAME ) )" $(stty size) 3>&1 1>&2 2>&3)
NAME2=$( echo $( git push ) ) 
whiptail --msgbox "$NAME2" $(stty size)