#!/bin/bash
libname=$(dirname "$0")
cd $libname
#set -x
bob(){ 
  tput smcup && clear


printf "Enter a Commit message: "
read -r  message
git add *
git commit -m "$message" 
git push; 

printf "Commit and push complete.\nEnter any key to continue... "
read -r
tput rmcup

}

git add *
#whiptail --infobox "$(echo $( git add * ))" $(stty size)
NAME=$(whiptail --inputbox "Please enter Comit message:" $(stty size) 3>&1 1>&2 2>&3)

whiptail --msgbox  "$(echo $( git commit -m $NAME ) )" $(stty size)
whiptail --msgbox "$(echo $(git push ) )" $(stty size)